name: Merge Checks
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install
        run: ./.devcontainer/install.sh

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
