name: Merge Checks
on: pull_request
jobs:  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Install
        run: npm install
      
      - name: Lint
        run: npm run lint
