name: Merge Checks
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: npm run lint

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
