name: Pull Request

on: [pull_request]

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Setup dependencies
        run: pnpm

      - name: Run checks
        run: pnpm lint
